/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteRouteImport } from './routes/_chat/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ChatChatThreadIdRouteImport } from './routes/_chat/chat.$threadId'

const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatThreadIdRoute = ChatChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => ChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof ChatIndexRoute
  '/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/api/chat' | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/api/chat' | '/' | '/chat/$threadId'
  id:
    | '__root__'
    | '/_chat'
    | '/sign-in'
    | '/api/chat'
    | '/_chat/'
    | '/_chat/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/chat/$threadId': {
      id: '/_chat/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatChatThreadIdRouteImport
      parentRoute: typeof ChatRouteRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatThreadIdRoute: typeof ChatChatThreadIdRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatChatThreadIdRoute: ChatChatThreadIdRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRouteRoute: ChatRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
