/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteRouteImport } from './routes/_chat/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSectionRouteImport } from './routes/settings/$section'
import { Route as SettingsCustomizationRouteImport } from './routes/settings/customization'
import { Route as SettingsHistoryRouteImport } from './routes/settings/history'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as ChatChatThreadIdRouteImport } from './routes/_chat/chat.$threadId'

const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCustomizationRoute = SettingsCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsHistoryRoute = SettingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ChatChatThreadIdRoute = ChatChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => ChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/api/chat': typeof ApiChatRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/': typeof SettingsIndexRoute
  '/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/api/chat': typeof ApiChatRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/api/chat': typeof ApiChatRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/customization': typeof SettingsCustomizationRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/models': typeof SettingsModelsRoute
  '/_chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_chat/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/sso-callback'
    | '/api/chat'
    | '/settings/$section'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/models'
    | '/settings/'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sso-callback'
    | '/api/chat'
    | '/settings/$section'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/models'
    | '/'
    | '/settings'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/sign-in'
    | '/sso-callback'
    | '/api/chat'
    | '/settings/$section'
    | '/settings/customization'
    | '/settings/history'
    | '/settings/models'
    | '/_chat/'
    | '/settings/'
    | '/_chat/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/customization': {
      id: '/settings/customization'
      path: '/customization'
      fullPath: '/settings/customization'
      preLoaderRoute: typeof SettingsCustomizationRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_chat/chat/$threadId': {
      id: '/_chat/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatChatThreadIdRouteImport
      parentRoute: typeof ChatRouteRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatThreadIdRoute: typeof ChatChatThreadIdRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatChatThreadIdRoute: ChatChatThreadIdRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsCustomizationRoute: typeof SettingsCustomizationRoute
  SettingsHistoryRoute: typeof SettingsHistoryRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsCustomizationRoute: SettingsCustomizationRoute,
  SettingsHistoryRoute: SettingsHistoryRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRouteRoute: ChatRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
